BEGIN
    -- Удаляем таблицы, если они существуют, чтобы избежать ошибок при создании новых
    FOR t IN (
        -- Выбираем названия таблиц, которые хотим удалить
        SELECT table_name 
        FROM user_tables 
        WHERE table_name IN ('STUDENTS', 'GROUPS', 'Documents', 'AUDIT_LOG', 'REPORTS_LOGS')
    ) LOOP
        -- Выполняем команду удаления таблицы с каскадным удалением ограничений
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- Таблица Students (Студенты)
CREATE TABLE Students (
    student_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    full_name    VARCHAR2(100) NOT NULL,
    birth_date   DATE,
    created_at   DATE DEFAULT SYSDATE,-- по умолчанию текущая дата
    CONSTRAINT pk_students PRIMARY KEY (student_id)
);

-- Таблица Groups (Группы)
CREATE TABLE Groups (
    group_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    student_id   NUMBER NOT NULL,
    group_name   VARCHAR2(200) NOT NULL,
    specialization VARCHAR2(100),
    start_date   DATE,-- Дата начала формирования группы
    created_at   DATE DEFAULT SYSDATE,-- по умолчанию текущая дата
    CONSTRAINT pk_groups PRIMARY KEY (group_id),
    CONSTRAINT fk_groups_student FOREIGN KEY (student_id)
       REFERENCES Students (student_id)
);

-- Таблица Documents (Экземпляры студентов)
CREATE TABLE Documents (
    copy_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    student_id   NUMBER NOT NULL,
    copy_number  VARCHAR2(50),-- Номер зачётки
    condition    VARCHAR2(100),-- Состояние доккумента
    created_at   DATE DEFAULT SYSDATE,
    CONSTRAINT pk_Documents PRIMARY KEY (copy_id),
    CONSTRAINT fk_Documents_student FOREIGN KEY (student_id)
       REFERENCES Students (student_id)
);

-- Таблица Audit_Log (Журнал изменений)
CREATE TABLE Audit_Log (
    audit_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    table_name    VARCHAR2(50),
    pk_value      VARCHAR2(100),
    changed_data  VARCHAR2(4000),
    operation_type CHAR(1),
    change_time   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_audit_log PRIMARY KEY (audit_id)
);

-- Таблица Reports_Logs (Журнал отчетов)
CREATE TABLE Reports_Logs (
    report_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    report_date    TIMESTAMP DEFAULT SYSTIMESTAMP,
    report_content  VARCHAR2(4000),
    CONSTRAINT pk_reports_logs PRIMARY KEY (report_id)
);

SELECT * FROM Groups;
SELECT * FROM Students;
SELECT * FROM Documents;
SELECT * FROM Audit_Log;
SELECT * FROM Reports_Logs;


DROP TABLE Groups;
DROP TABLE Documents;
DROP TABLE Students;
DROP TABLE Audit_Log;
DROP TABLE Reports_Logs;


TRUNCATE TABLE  Groups;
TRUNCATE TABLE  Documents;
TRUNCATE TABLE  Students;
TRUNCATE TABLE  Audit_Log;
TRUNCATE TABLE  Reports_Logs;
