-- Создание таблицы
CREATE TABLE STUDENTS_AUDIT
(
    AUDIT_ID NUMBER PRIMARY KEY,
    ACTION_TYPE VARCHAR2(10),
    ACTION_TIME TIMESTAMP,
    USER_NAME VARCHAR2(255),
    STUDENT_ID NUMBER,
    STUDENT_NAME VARCHAR2(255),
    GROUP_ID NUMBER,
    OLD_VALUE VARCHAR2(255),
    NEW_VALUE VARCHAR2(255)
);

-- Создание последовательности
CREATE SEQUENCE STUDENTS_AUDIT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Создание триггера для вставки
CREATE OR REPLACE TRIGGER AUDIT_INSERT_STUDENTS
AFTER INSERT ON STUDENTS
FOR EACH ROW
BEGIN
    INSERT INTO STUDENTS_AUDIT (AUDIT_ID, ACTION_TYPE, ACTION_TIME, USER_NAME, STUDENT_ID, STUDENT_NAME, GROUP_ID, NEW_VALUE)
    VALUES (STUDENTS_AUDIT_SEQ.NEXTVAL, 'INSERT', SYSDATE, USER, :NEW.ID, :NEW.NAME, :NEW.GROUP_ID, 'New student added');
END AUDIT_INSERT_STUDENTS;
/

-- Создание триггера для обновления
CREATE OR REPLACE TRIGGER AUDIT_UPDATE_STUDENTS
AFTER UPDATE ON STUDENTS
FOR EACH ROW
BEGIN
    INSERT INTO STUDENTS_AUDIT (AUDIT_ID, ACTION_TYPE, ACTION_TIME, USER_NAME, STUDENT_ID, STUDENT_NAME, GROUP_ID, OLD_VALUE, NEW_VALUE)
    VALUES (STUDENTS_AUDIT_SEQ.NEXTVAL, 'UPDATE', SYSDATE, USER, :NEW.ID, :NEW.NAME, :NEW.GROUP_ID, :OLD.NAME, :NEW.NAME);
END AUDIT_UPDATE_STUDENTS;
/

-- Создание триггера для удаления
CREATE OR REPLACE TRIGGER AUDIT_DELETE_STUDENTS
AFTER DELETE ON STUDENTS
FOR EACH ROW
BEGIN
    INSERT INTO STUDENTS_AUDIT (AUDIT_ID, ACTION_TYPE, ACTION_TIME, USER_NAME, STUDENT_ID, STUDENT_NAME, GROUP_ID, OLD_VALUE)
    VALUES (STUDENTS_AUDIT_SEQ.NEXTVAL, 'DELETE', SYSDATE, USER, :OLD.ID, :OLD.NAME, :OLD.GROUP_ID, 'Student deleted');
END AUDIT_DELETE_STUDENTS;
/


INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (5, 'ПАша', 1);
SELECT * FROM STUDENTS_AUDIT;






SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS WHERE TRIGGER_NAME IN 
('AUDIT_INSERT_STUDENTS', 'AUDIT_UPDATE_STUDENTS', 'AUDIT_DELETE_STUDENTS');



DROP TABLE STUDENTS_AUDIT;
DROP SEQUENCE STUDENTS_AUDIT_SEQ;
DROP TRIGGER AUDIT_INSERT_STUDENTS;
DROP TRIGGER AUDIT_UPDATE_STUDENTS;
DROP TRIGGER AUDIT_DELETE_STUDENTS;
