SELECT * FROM GROUPS;
SELECT * FROM STUDENTS;

INSERT INTO GROUPS ( NAME) VALUES ( 'Группа A');

INSERT INTO GROUPS (ID, NAME) VALUES (1, 'Группа A');

INSERT INTO GROUPS (ID, NAME) VALUES (2, 'Группа Б');

INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (1, 'Иван', 1);
INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (2, 'Мария', 1);
INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (3, 'Паша', 2);
INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Саша', 1);
INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Маша', 2);


DELETE FROM GROUPS WHERE ID = 1; 

EXEC delete_group_and_students(2);


SELECT * FROM Student_logs;


BEGIN
    restore_data_from_audit(0, TO_TIMESTAMP('2025-03-05 18:21:48', 'YYYY-MM-DD HH24:MI:SS'));
END;
/

BEGIN
    restore_data_from_audit(0, SYSTIMESTAMP - INTERVAL '30' SECOND);
END;
/




BEGIN
    RESTORE_STUDENT(1);
END;


